services:
  mediamtx:
    image: bluenviron/mediamtx
    container_name: mediamtx
    restart: always
    ports:
      - "8554:8554"
      - "8888:8888"
      - "8889:8889/udp"
      - "8890:8890/udp"
      - "8189:8189/udp"
    environment:
      - MTX_RTSPTRANSPORTS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=192.168.1.111